name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  tf-validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      - run: terraform init -backend=false
      - run: terraform fmt -check
      - run: terraform validate
